"$schema": https://json-schema.org/draft/2020-12/schema
description: 'Schema for the MOD-DCAT-Profile building block'
type: object
properties:
  a:
    type: string
    format: uri
  b:
    type: number
required:
  - a
  - b
